### ISSUE TITLE
Trying to build in CloudPebble, won't build

### ISSUE THREAD

**Issue by dustdingo** [chanomie/pebble-tcplights#1]
Hello!

Looking forward to using this app - love our TCP lights and can't wait to control them on the Pebble! I tried first to find it in the Pebble store, but it's nowhere to be found. I've gone ahead and imported the project into CloudPebble, but I keep getting a compile error. I've pasted the build log below, but the specific error I'm seeing is:

File "/app/sdk2/Pebble/tools/pbpack.py", line 57, in serialize_table
    raise Exception("The last resource cannot be identical to a previous one")
Exception: The last resource cannot be identical to a previous one
Waf: Leaving directory `/tmp/tmpte5ilZ/build'
Build failed
 -> task in 'app_resources.pbpack.table' failed (exit status 1): 
    {task 139678057456528: app_resources.pbpack.table menu_icon.png.pbi,logo_splash.png.pbi,tile_splash.png.pbi,UbuntuMono-Regular.ttf.MONO_FONT_14.pfo,tcpicon.png.pbi,menu_icon.png.pbi,pbpack_meta_data.py -> app_resources.pbpack.table}
' python \'/app/sdk2/Pebble/tools/pbpack_meta_data.py\' table \'/tmp/tmpte5ilZ/build/app_resources.pbpack.table\' "/tmp/tmpte5ilZ/build/resources/images/menu_icon.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/logo_splash.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/tile_splash.png.pbi"  "/tmp/tmpte5ilZ/build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo"  "/tmp/tmpte5ilZ/build/resources/images/tcpicon.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/menu_icon.png.pbi"  '
[ERROR   ] A compilation error occurred

Any ideas? Thanks!!

Setting top to                           : /tmp/tmpte5ilZ 
Setting out to                           : /tmp/tmpte5ilZ/build 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK in          : /app/sdk2/Pebble
'configure' finished successfully (0.110s)
Waf: Entering directory `/tmp/tmpte5ilZ/build'
[ 3/30] menu_icon.png.pbi: resources/images/menu_icon.png ../../app/sdk2/Pebble/tools/bitmapgen.py -> build/resources/images/menu_icon.png.pbi
[ 2/30] appinfo.auto.c: appinfo.json -> build/appinfo.auto.c
[ 4/30] tile_splash.png.pbi: resources/images/tile_splash.png ../../app/sdk2/Pebble/tools/bitmapgen.py -> build/resources/images/tile_splash.png.pbi
[ 3/30] logo_splash.png.pbi: resources/images/logo_splash.png ../../app/sdk2/Pebble/tools/bitmapgen.py -> build/resources/images/logo_splash.png.pbi
[ 5/30] UbuntuMono-Regular.ttf.MONO_FONT_14.pfo: resources/fonts/UbuntuMono-Regular.ttf ../../app/sdk2/Pebble/tools/font/fontgen.py -> build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo
[ 6/30] tcpicon.png.pbi: resources/images/tcpicon.png ../../app/sdk2/Pebble/tools/bitmapgen.py -> build/resources/images/tcpicon.png.pbi
[ 7/30] menu_icon.png.pbi: resources/images/menu_icon.png ../../app/sdk2/Pebble/tools/bitmapgen.py -> build/resources/images/menu_icon.png.pbi
[ 8/30] pebble-js-app.js: src/js/app.js src/js/lib/ajax.js src/js/lib/emitter.js src/js/lib/image.js src/js/lib/myutil.js src/js/lib/safe.js src/js/lib/struct.js src/js/lib/util2.js src/js/lib/vector2.js src/js/loader.js src/js/main.js src/js/settings/index.js src/js/settings/settings.js src/js/simply/simply.js src/js/smartpackage/package-pebble.js src/js/smartpackage/package.js src/js/ui/accel.js src/js/ui/card.js src/js/ui/circle.js src/js/ui/element.js src/js/ui/image.js src/js/ui/imageservice.js src/js/ui/index.js src/js/ui/inverter.js src/js/ui/menu.js src/js/ui/propable.js src/js/ui/rect.js src/js/ui/resource.js src/js/ui/simply-pebble.js src/js/ui/simply.js src/js/ui/stage.js src/js/ui/tests.js src/js/ui/text.js src/js/ui/timetext.js src/js/ui/vibe.js src/js/ui/window.js src/js/ui/windowstack.js src/js/vendor/moment.js src/js/vendor/png.js src/js/vendor/zlib.js -> build/src/js/pebble-js-app.js
[ 9/30] app_resources.pbpack.table: build/resources/images/menu_icon.png.pbi build/resources/images/logo_splash.png.pbi build/resources/images/tile_splash.png.pbi build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo build/resources/images/tcpicon.png.pbi build/resources/images/menu_icon.png.pbi ../../app/sdk2/Pebble/tools/pbpack_meta_data.py -> build/app_resources.pbpack.table
[10/30] app_resources.pbpack.data: build/resources/images/menu_icon.png.pbi build/resources/images/logo_splash.png.pbi build/resources/images/tile_splash.png.pbi build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo build/resources/images/tcpicon.png.pbi build/resources/images/menu_icon.png.pbi ../../app/sdk2/Pebble/tools/pbpack_meta_data.py -> build/app_resources.pbpack.data
[11/30] app_resources.pbpack.manifest: build/resources/images/menu_icon.png.pbi build/resources/images/logo_splash.png.pbi build/resources/images/tile_splash.png.pbi build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo build/resources/images/tcpicon.png.pbi build/resources/images/menu_icon.png.pbi ../../app/sdk2/Pebble/tools/pbpack_meta_data.py -> build/app_resources.pbpack.manifest
[12/30] resource_ids.auto.h: build/resources/images/menu_icon.png.pbi build/resources/images/logo_splash.png.pbi build/resources/images/tile_splash.png.pbi build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo build/resources/images/tcpicon.png.pbi build/resources/images/menu_icon.png.pbi ../../app/sdk2/Pebble/tools/generate_resource_code.py build/app_resources.pbpack.data -> build/src/resource_ids.auto.h
Traceback (most recent call last):
  File "/app/sdk2/Pebble/tools/pbpack_meta_data.py", line 67, in <module>
    main()
  File "/app/sdk2/Pebble/tools/pbpack_meta_data.py", line 64, in main
    args.func(args)
  File "/app/sdk2/Pebble/tools/pbpack_meta_data.py", line 19, in cmd_table
    table_bytes = pack.serialize_table()
  File "/app/sdk2/Pebble/tools/pbpack.py", line 57, in serialize_table
    raise Exception("The last resource cannot be identical to a previous one")
Exception: The last resource cannot be identical to a previous one
Waf: Leaving directory`/tmp/tmpte5ilZ/build'
Build failed
 -> task in 'app_resources.pbpack.table' failed (exit status 1): 
    {task 139678057456528: app_resources.pbpack.table menu_icon.png.pbi,logo_splash.png.pbi,tile_splash.png.pbi,UbuntuMono-Regular.ttf.MONO_FONT_14.pfo,tcpicon.png.pbi,menu_icon.png.pbi,pbpack_meta_data.py -> app_resources.pbpack.table}
' python \'/app/sdk2/Pebble/tools/pbpack_meta_data.py\' table \'/tmp/tmpte5ilZ/build/app_resources.pbpack.table\' "/tmp/tmpte5ilZ/build/resources/images/menu_icon.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/logo_splash.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/tile_splash.png.pbi"  "/tmp/tmpte5ilZ/build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo"  "/tmp/tmpte5ilZ/build/resources/images/tcpicon.png.pbi"  "/tmp/tmpte5ilZ/build/resources/images/menu_icon.png.pbi"  '
[ERROR   ] A compilation error occurred

**Comment by chanomie** [comment]
It stopped working - it works by making REST API calls to lighting.local, but an update to TCP lights seems to have broken that interface. I got multiple reports on te Pebble Store it stopped working for people - so I pulled the app. 

Not sure why it's not importing. I think you can just fork it and then use the CloudPebble GitHub integration to build.

**Comment by dustdingo** [comment]
That's unfortunate - I'd love to be able to control the lights without upgrading to a Smartthings router. Did you by chance happen to see this article? I stumbled across it while I was searching for possible solutions, so I wasn't sure if this would fix the API issue.

http://home.stockmopar.com/updated-connected-by-tcp-api/

**Comment by chanomie** [comment]
That's the update that broke it. I didn't realize Stockmopar had figured out the mDNS/Bonjour issue. It does look like it's fixable.

**Comment by dustdingo** [comment]
That's good news! You think you have any interest in continued development? Or is this a past project for you? I'm just now getting into learning coding, so even if I wanted to pick up where you left off this is somewhat outside of my skill set. Though I'd be happy to help out in any way that I could and may continue to research it to see if I can learn through fiddling. Thanks again for laying the groundwork!
